# Generated by Django 3.1.6 on 2021-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buguser',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
    ]
