# Generated by Django 3.1.6 on 2021-06-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_admin', to='bug.userprofile'),
        ),
    ]
